version: '3.8'

services:

  postgres1:
    image: postgres:15
    container_name: product-postgres
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network

  product-service:
    build: .
    container_name: product-service
    depends_on:
      - postgres1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-postgres:5432/products
   #   SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/products
  #    SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mypass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: my-rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8084:8082"
    volumes:
      - ./logs:/app/logs # Opsiyonel
    command: ["java", "-jar", "/app/.jar"] # Doğru başlatma komutunu ekleyin
    networks:
      - shared-network

volumes:
  postgres_data:

networks:
  shared-network:
    external: true