version: '3.8'

services:
  userservice:
    build: .
    container_name: userservice
    depends_on:
      postgres3:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres3:5432/userservice
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_RABBITMQ_HOST=my-rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    networks:
      - app-network
    command: ["java", "-jar", "/app/userservice.jar"]  # Runs your JAR file
    volumes:
      - ./target/userservice-0.0.1-SNAPSHOT.jar:/app/userservice.jar  # Mount built JAR

  postgres3:
    image: postgres:15
    container_name: postgres3
    restart: always
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d userservice"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:

volumes:
  pgdata:
